#7 feature(lab7): Реализовал 7 лабораторную работу
inittose/OOP pull request #11
Opened 2024-03-16 11:52 UTC by inittose

- Добавил статический класс DataTools, который работает с данными товаров
- Реализовал функции с делегатом
- На вкладке ItemsTab реализовал логику поиска и сортировки товаров

2024-03-16 16:53 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Address.cs
> +                this.Index,
Убрать this

2024-03-16 17:00 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Address.cs
> +            var result = this.Index == other.Index;
убрать this

2024-03-16 17:06 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Cart.cs
> +            foreach(var item in this.Items)
убрать this. Исправь во всем проекте.

2024-03-16 17:20 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Address.cs
>          /// Разряд почтового индекса.
Прощу прощения, что раньше не обратил внимания, константы именуются с использованием стиля Паскаль. Исправить во всем проекте :)

2024-03-16 17:32 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Discounts/PercentDiscount.cs
> +                ValueValidator.AssertIntOnLimits(value, 1, 10, nameof(Discount));
Магические числа

2024-03-16 19:21 UTC, Nikita-Isaichenko requested changes

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Discounts/PercentDiscount.cs
> +            var percentage = (int)(SpendingPerCategory / 1000) + 1;
Все магические числа исправить

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Discounts/PointsDiscount.cs
> +            return discount;
добавить перед return строку пустую

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Item.cs
> +            var item = new Item(this.Id);
this

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Item.cs
> +            return item;
перед return строку. Везде

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Item.cs
> +            if (this.Cost == other.Cost)
this

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Orders/Order.cs
> +        public double Total
Тут конечную стоимость ты хранишь в double, в свойстве Amount - в float, привести к одному типу, double. Проверь везде, где хранишь информацию о стоимости и измени на double

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Orders/Order.cs
> +            return this.Id == other.Id;
this

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Orders/PriorityOrder.cs
> +        public DateTime Date { get; set; }
Лучше, наверное, DeliveryDate и ниже DeliveryTime, чтобы было сразу понятно, что означает эта переменная

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Orders/PriorityOrder.cs
> +
Убрать лишнюю строку

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/CustomerFactory.cs
>          private const int MAX_POST_INDEX = 999999;
Именование констант

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/DataTools.cs
> +    /// Фильтрует и сортирует данные.
Я бы в комментарии написал: "Хранит логику по обработке данных". Сейчас название класса слишком обобщенное по сравнению с тем, что указано в комментарии

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CartsTab.cs
> +                AmountLabel.Visible = isVisible;
Установку свойств видимости можно вынести в отдельный метод в этом же классе, чтобы убрать лишний код из сеттера

2024-03-16 19:21 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CartsTab.cs
> +        public double DiscountAmount { get; set; }
Комментарий

2024-03-20 09:43 UTC, CephalonGL requested changes

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Address.cs
> +        public bool Equals(Address other)
Реализация метода Equals должна использовать сравнение хеш-кодов двух Address. Метод расчёта хеш-кода уже объявлен в интерфейсе IEquatable

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Discounts/PointsDiscount.cs
> +            if (Points / amount > 0.3)
Убрать магические числа

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Discounts/PointsDiscount.cs
> +            Points += (int)Math.Ceiling(amount * 0.1);
Магическое число

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Discounts/PointsDiscount.cs
> +        /// Скидка товаров не может быть больше 30% от общей суммы товаров.
Избегай ссылок на численные параметры в комментариях, потому что если в процессе разработки требования к ПО поменяются и это значение изменится, то это значение в комментарии тоже придётся менять. К тому же, про это место можно забыть и не исправить после изменения значения в программе и из-за этого документация станет недостоверной.

Магическое число вынеси в константу и в комментарии сделай ссылку на созданное поле/свойство константы через see cref

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Enums/OrderTime.cs
> +        FromNineToElevenAM,
Добавить XML-комментарий к каждому элементу перечисления. Исправить во всём решении

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Item.cs
> +        public bool Equals(Item other)
Сравнение по хеш-коду. Исправить во всём решении

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Orders/Order.cs
> +        public double Total
Для хранения валюты нужно использовать decimal

float, double и decimal являются представлениями чисел с плавающей запятой. Из-за особенности представления чисел с плавающей запятой в памяти компьютера, при выполнении арифметических операций над ними, возникает погрешность. Это недопустимо при расчёте денежных средств. Для решения этой проблемы существует специальный тип данных - decimal

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/DataTools.cs
> +            foreach (var item in items)
Списки поддерживают клонирование. Использовать встроенный метод Clone() вместо самостоятельного копирования

2024-03-20 09:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/MainForm.cs
> +                    CustomersTab.UpdateDiscountsListBox();
Обернуть содержимое кейсов в фигурные скобки

2024-03-26 06:49 UTC, CephalonGL requested changes

2024-03-26 06:49 UTC, CephalonGL commented on doc/Practics7.png
См. замечания в дс

2024-03-27 11:42 UTC, Nikita-Isaichenko requested changes

2024-03-27 11:42 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Discounts/PercentDiscount.cs
> +            var percentage = (int)(SpendingPerCategory / 1000) + 1;
а тут что за числа, ты так и не исправил

2024-04-01 09:41 UTC, CephalonGL approved these changes

2024-04-01 14:03 UTC, Nikita-Isaichenko approved these changes

2024-04-01 14:03 UTC, merged