Лабораторная работа 1 готова к проверке.
inittose/OOP pull request #4
Opened 2024-02-15 06:26 UTC by inittose

## Изменения в репозитории:
- Переименовал ветку lab1 -> feature/lab1
- создал develop, куда буду заливать коммиты с feature/..

2024-02-15 10:26 UTC, CephalonGL requested changes

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Customer.cs
> +            get
Для аксессоров (геттеров, сеттеров, тд), записанных в одну строку, используй запись в виде выражения get => _value;
Исправь во всём решении

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Item.cs
> +                if (value < 0 || value > 100000f)
1. Перенести эту проверку в класс валидатора. У тебя уже есть класс валидатора, который выполняет валидацию значений (например, по макс. длине), это значит, что подобные проверки следует делегировать ему. Потому что этот код потом можно переиспользовать, а значит уменьшить его дублирование и сократить время на написание новой функциональности
2. Любые магические числа следует выносить в отдельные переменные, это облегчает чтение кода как тебе, так и другим

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Customer.cs
> +    internal class Customer
Модификатор internal позволяет использовать этот класс только внутри данной сборки (проекта). В контексте лабораторных по этому предмету это не имеет значения, однако ты должен понимать, в чём значение этого модификатора, если его используешь. Если этот класс нужно будет покрыть юнит-тестами (которые описываются в другом проекте), то этого сделать не получится без изменения модификатора доступа на public. Подробнее о модификаторах доступа читать вот тут: https://metanit.com/sharp/tutorial/3.2.php

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Item.cs
> +                    throw new ArgumentException("Cost is not included in the range from 0 to 100 000.");
Тут сообщение на английском, а в валидаторе - на русском. Сделать единообразно

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/IdGenerator.cs
> +        static public int GetNextId()
Сначала указывается модификатор доступа, потом модификатор static (см. стандарт оформления кода RSDN)

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +            bool status = selectedIndex >= 0;
По названию переменной status не понятно, за что она отвечает. Для флагов лучше использовать стиль именования isSomething, например, isSelectedIndexCorrect. Переименовать

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +            if (removeIndex != -1)
Обращай внимание на вложенность метода. Чем больше вложенность, тем сложнее воспринимать код разработчику. В данном случае можно убрать лишний уровень вложенности инвертировав это условие:
if (removeIndex == -1)
{
return;
}

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +                if (CustomersListBox.Items.Count > 0)
Инвертировать условие

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +            _items.Add(newItem);
Запрещено обращаться к приватному полю в обход аксессора. Обернуть _items в свойство или заменить его на авто-свойство.

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +            if (removeIndex != -1)
Инвертировать

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +                if (ItemsListBox.Items.Count > 0)
Инвертировать

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +            else if (getParse > 100000)
Вынести "магические числа в переменную или константу

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +            else if (NameTextBox.Text.Length > 200)
"Магическое число"

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +            if (DescriptionTextBox.Text.Length > 1000)
"Магическое число"

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/IdGenerator.cs
> +    static internal class IdGenerator
Сначала идёт модификатор доступа internal: internal static class
См. стандарт оформления кода RSDN: https://www.rsdn.org/article/mag/200401/codestyle.XML

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +    public partial class CustomersTab : UserControl
XML

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +        public CustomersTab()
XML. Исправить во всём решении

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +        private Color rightInputColor = Color.White;
XML

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +        private Color wrongInputColor = Color.Red;
XML

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +            _customers.Add(newCustomer);
Обернуть в свойство

2024-02-15 10:26 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +            else if (FullNameTextBox.Text.Length > 200)
"Магические числа"
Исправить во всём решении

2024-02-15 10:54 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +            int removeIndex = CustomersListBox.SelectedIndex;
Цитирую моего ревьювера "Старайся использовать var везде, где не нужно явно указывать тип при создании переменной, исключением является цикл for. На работу программы не влияет, есть аргументы за и против var, но такая политика компании."

2024-02-15 10:59 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +using System.Windows.Forms;
Удалить не использующиеся using, также и в других файлах

2024-02-15 11:20 UTC, Nikita-Isaichenko requested changes

2024-02-15 11:20 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +using System.Windows.Forms;
Удалить не использующиеся using, также и в других файлах

2024-02-15 11:20 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +            int removeIndex = CustomersListBox.SelectedIndex;
Цитирую моего ревьювера "Старайся использовать var везде, где не нужно явно указывать тип при создании переменной, исключением является цикл for. На работу программы не влияет, есть аргументы за и против var, но такая политика компании."

2024-02-17 05:24 UTC, inittose commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +            _items.Add(newItem);
Правильно ли я понимаю, что свойство может быть как `private`, так и `public`? При этом стандарт написания имени свойства также будет использовать стиль `Паскаль` для регистра букв?

> Пример, что я имею ввиду: то есть к закрытому полю `_items` можно создать свойство как `public List<Item> Items`, так и `private List<Item> Items`

2024-02-17 20:26 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Customer.cs
> +        private static readonly int _fullnameLengthLimit = 200;
Зачем static readonly, не проще ли использовать const?

2024-02-17 21:27 UTC, Nikita-Isaichenko requested changes

2024-02-17 21:27 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/IdGenerator.cs
> +        private static int Counter
Сделай автоматическим свойством

2024-02-17 21:27 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/Serializer.cs
> +        public static String FilePath
Если в сеттере или геттере не производишь никаких действий с переменной, то лучше использовать авто свойства, это позволит уменьшить код

2024-02-17 21:27 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +        private List<Customer> _customers = Serializer.GetCustomers();
Можно объявить как авто свойство и сразу в него присвоить. Посмотреть во всем коде

2024-02-17 21:27 UTC, Nikita-Isaichenko commented on doc/Practics1.png
Стрелки от CustomerFactory, ItemFactory, Serializer

2024-02-19 05:30 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/ItemFactory.cs
> +        private static String FileName { get; } =
Это не замечание, просто предложение добавить set, чтобы можно было например указывать другие пути к базам данным.

2024-02-19 05:33 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +        private static Color RightInputColor { get; } = Color.White;
А можешь объяснить зачем ты используешь static?

2024-02-19 05:45 UTC, Nikita-Isaichenko requested changes

2024-02-19 05:45 UTC, Nikita-Isaichenko commented on doc/Practics1.png
Ты указал стрелки для реализации, реализация применяется для обозначения классов, которые реализуют интерфейсы, здесь уже у тебя обычное использование.

2024-02-19 12:11 UTC, inittose commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/ItemFactory.cs
> +        private static String FileName { get; } =
Конечно можно, но в данном классе такой функционал пока не реализован.

2024-02-19 12:13 UTC, inittose commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
> +        private static Color RightInputColor { get; } = Color.White;
Для данного класса бессмысленно, как я только что понял. У нас же только один объект данного класса будет использоваться, поэтому нет смысла для static.

2024-02-19 12:43 UTC, CephalonGL requested changes

2024-02-19 12:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Item.cs
> +            Name = String.Empty;
String - класс из пространства имён System, а string - alias (псевдоним), за которым скрывается System.String. Поведение программы не меняется (только если его не переопределять для string), но используй string (первая - строчная)

2024-02-19 12:43 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +        private void CustomersListBox_SelectedIndexChanged(object sender, EventArgs e)
XML. Исправить во всём решении

2024-02-19 13:07 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CustomersTab.cs
> +            Customer newCustomer = new Customer();
Используй var вместо типов

2024-02-19 13:25 UTC, Nikita-Isaichenko approved these changes

2024-02-19 13:31 UTC, CephalonGL approved these changes

2024-02-19 13:31 UTC, merged