#2 feature(lab2): Реализовал 2 лабораторную работу
inittose/OOP pull request #6
Opened 2024-02-22 08:21 UTC by inittose

- Добавил перечисление Category и внедрил в класс Item
- Добавил класс Address, написал логику к нему и внедрил в проект
- Добавил класс Store, переписал сериализацию и внедрил в проект
- Также переписал ItemFactory и CustomerFactory для корректной генерации

2024-02-22 12:12 UTC, Nikita-Isaichenko requested changes

2024-02-22 12:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Store.cs
> +using System.Threading.Tasks;
Лишние using. Во всем проекте

2024-02-22 12:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/CustomerFactory.cs
> +        /// Минимальное значение почтового индекса
Точка в конце предложения. Снизу тоже

2024-02-22 12:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/CustomerFactory.cs
> +            return RandomPostIndex;
Можно сократить и сразу вернуть random.Next....

2024-02-22 12:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/ItemFactory.cs
> +            var randomItem = new Item(itemName, itemInfo, itemCost, randomCategory);
здесь тоже можно сократить и сразу вернуть new Itew(...)

2024-02-22 12:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Controls/AddressControl.cs
> +        private Color RightInputColor { get; } = Color.White;
В ItemTab ты тоже используешь такие переменные (нарушаешь принцип Don’t repeat yourself), сделай их static readonly и вынеси в static класс, который можешь назвать, типо AppColor

2024-02-22 12:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/ItemsTab.cs
>          /// Инициализировать компонент,
пиши комментарии в стиле "что делает" - "инициализирует"

2024-02-22 12:39 UTC, Nikita-Isaichenko requested changes

2024-02-22 12:39 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/AppColors.cs
> +    public static class AppColors
Комментарий для класса

2024-02-22 12:39 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/Serializer.cs
> +        /// Сериализовать данные о товарах и покупателях и сохранить изменения.
сериализует и сохраняет, используй вопрос "что делает?" когда пишешь комментарии

2024-02-22 12:39 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/Serializer.cs
> +        /// Десериализовать данные о товарах и покупателях.
десериализует

2024-02-22 13:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/CustomerFactory.cs
> +        /// Получает экзепляр класса <see cref="Customer"/> с начальными случайными значениями.
не получает, а возвращает

2024-02-22 13:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/CustomerFactory.cs
> +        /// Получает случайный почтовый индекс.
Возвращает

2024-02-22 13:12 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/ItemFactory.cs
> +        /// Получает экзепляр класса <see cref="Item"/> с начальными случайными значениями.
Возвращает

2024-02-22 13:13 UTC, Nikita-Isaichenko approved these changes

2024-02-26 04:28 UTC, CephalonGL requested changes

2024-02-26 04:28 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Address.cs
> +        public Address(int index, string country, string city,
Если выполняешь перенос аргументов, то нужно, чтобы каждый аргумент находился на своей строке (первый аргумент тоже переносится). При этом все аргументы отстоят на одну табуляцию от объявления метода (но это тебе IDE сделает сама, скорее всего)

2024-02-26 04:28 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/CustomerFactory.cs
>              $@"{Directory.GetCurrentDirectory()}\..\..\Services\Databases\CustomersData.txt";
Вместо абсолютных путей используй относительные. Для этого используй две точки "../"вместо {Directory.GetCurrentDirectory()}. Твой подход будет тоже работать, как и относительные, но я всё равно рекомендую использовать относительные, потому что они выглядят лаконичнее

2024-03-01 09:38 UTC, CephalonGL approved these changes

2024-03-01 09:39 UTC, merged