#3 feature(lab3): Реализовал 3 лабораторную работу
inittose/OOP pull request #7
Opened 2024-03-01 10:30 UTC by inittose

- Добавил классы Cart и Order, а также перечисление OrderStatus
- Добавил 2 вкладки: CartsTab и OrdersTab
- Реализовал логику для вкладок
- Реализовал логику предотвращения конфликтов использования Id
- Сериализация действует теперь на некоторые readonly поля

2024-03-01 11:43 UTC, Nikita-Isaichenko approved these changes

2024-03-01 14:55 UTC, CephalonGL requested changes

2024-03-01 14:55 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Cart.cs
> +        public float Amount
Дублирование кода с классом Order. Вынести расчёты в отдельный метод в отдельном классе и переиспользовать везде

2024-03-01 14:55 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Order.cs
> +        public float Amount
Дублирование

2024-03-01 14:55 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CartsTab.cs
> +            for (var i = 0; i < Customers.Count; i++)
Циклы foreach лучше читаются. Если ничего не мешает их использовать, следует это делать. Заменить на foreach.

2024-03-01 14:55 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CartsTab.cs
> +            for (var i = 0; i < cart.Items.Count; i++)
foreach

2024-03-01 14:55 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/OrdersTab.cs
> +            foreach (Customer customer in Customers)
Используй var вместо конкретных типов везде, где это возможно. Исправить во всём решении.

2024-03-13 12:13 UTC, CephalonGL approved these changes

2024-03-13 12:13 UTC, merged