#4 feature(lab4): Реализовал 4 лабораторную работу
inittose/OOP pull request #8
Opened 2024-03-12 13:44 UTC by inittose

- Добавил класс PriorityOrder и перечисление OrderTime
- Реализовал логику приоритетных покупателей и их заказов
- Обновил UML-диаграмму

2024-03-13 17:17 UTC, Nikita-Isaichenko requested changes

2024-03-13 17:17 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/Model/Cart.cs
> +        /// Список товаров <see cref="Item"/> в корзине.
Свойства комментируй единообразно, добавь "Возвращает и задает...". Проверь во всем коде

2024-03-13 17:17 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CartsTab.cs
> +
Убрать лишнюю строку. "Используйте одну пустую строку между логическими частями в методе" из RSDN. Проверить везде

2024-03-13 17:17 UTC, Nikita-Isaichenko commented on ObjectOrientedPractics/ObjectOrientedPractics/View/Tabs/CartsTab.cs
> +            }
Стоит поставить пустую строку. https://rsdn.org/article/mag/200401/codestyle.XML прочитай здесь когда ставится пустая строка, а когда нет, проверь по всему коду

2024-03-15 12:27 UTC, Nikita-Isaichenko approved these changes

2024-03-16 18:37 UTC, CephalonGL requested changes

2024-03-16 18:37 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/ItemFactory.cs
>              var randomCategory = (Category)random.Next(0, Enum.GetNames(typeof(Category)).Length);
Из-за того, то в одной строке делаешь много действий одновременно, падает читаемость кода. Когда это будет читать другой разработчик или ты через пару недель, будет труднее в этом разобраться. Поэтому всегда, когда пишешь код, старайся его оформлять его так, чтобы его можно было легче понять читающему. Расписать в несколько строк

2024-03-16 18:37 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/View/MainForm.cs
> +                case 2:
Содержимое кейсов обернуть в фигурные скобки

2024-03-16 18:37 UTC, CephalonGL commented on ObjectOrientedPractics/ObjectOrientedPractics/Services/Serializer.cs
> +                    MessageBox.Show("Данные повреждены.\nФайлы сохранения очищены.");
Здесь на русском, в остальных местах программы - на английском. Сделать единообразно

2024-04-01 14:03 UTC, merged